# -*- coding: utf-8 -*-
"""save_melspectrogram.ipynb

Automatically generated by Colaboratory.


"""

import os
import numpy as np
import librosa
import librosa.display
#from sklearn.preprocessing import scale
import matplotlib.pyplot as plt

def save_melspectrogram(dir_path, filename, save_path, sampling_rate=44100):
  file_path = dir_path + filename
  data, sr = librosa.load(file_path,sr=sampling_rate, mono=True)
  #data = scale(data)

  melspec = librosa.feature.melspectrogram(y=data, sr=sr, n_mels=128)
  log_melspec = librosa.power_to_db(melspec, ref=np.max)  
  librosa.display.specshow(log_melspec, sr=sr)

  plt.savefig(save_path + filename[:-4] + '.png')

dir_path = './dataset/cough_5sec/'
save_path = '/dataset/spec/cough_spec/'

files = os.listdir(dir_path)

for file in files:
  save_melspectrogram(dir_path, file, save_path)
    print(file)  # 완료한 file명 확인

print('len cough : ',len(os.listdir('./dataset/spec/cough_spec/')))
print('len non : ',len(os.listdir('./dataset/spec/non_spec/')))